name: Build & Test then Deploy To Azure and Test EndPoints

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: "APINET8"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
run-name: Build & Test xUnit by @${{ github.actor }} on ${{ github.ref }}
jobs:
  Build-Solution:
    name: Build Solution
    runs-on: windows-latest   
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Build solution
        run: dotnet build -c Release

  xUnit-Test:
    name: xUnit Test
    runs-on: windows-latest   
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    needs: Build-Solution

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run xUnit Test
        run: dotnet test ./Test.APINET8/Test.APINET8.csproj  --verbosity normal --logger "trx;LogFileName=test-results.trx" 
        
      - name: Report Test
        uses: dorny/test-reporter@v1
        with:
          name: Publish xUnit Test Result
          reporter: dotnet-trx
          path: "**/test-results.trx"  
          fail-on-error: 'true'
          fail-on-empty: 'true'
